/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paniscode.pl_pa;

import java.util.List;
import java.util.concurrent.Semaphore;
import javax.swing.JTextPane;

/**
 *
 * @author alvaro
 */
public class InterfazP1 extends javax.swing.JFrame {

    private Boolean parado;
    
    private final Object espera_Control = new Object(); //"monitor para esperar si se detiene la ejecucion" 
    
    private Semaphore ster1 = new Semaphore(1); //para acceso a los tuneles de entrada al refugio
    private Semaphore ster2 = new Semaphore(1); //STER(semaforo tunel entrada refugio x)
    private Semaphore ster3 = new Semaphore(1);
    private Semaphore ster4 = new Semaphore(1);
    
    private Semaphore stsr1 = new Semaphore(1); //para acceso a los tuneles de salida del refugio
    private Semaphore stsr2 = new Semaphore(1); //STSR(semaforo tunel salida refugio x)
    private Semaphore stsr3 = new Semaphore(1);
    private Semaphore stsr4 = new Semaphore(1);
    /**
     * Creates new form InterfazP1
     * @param parado
     */
    public InterfazP1() {
        this.parado = true;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        RefugioPanel = new javax.swing.JPanel();
        RefugioH = new javax.swing.JLabel();
        ZonaComunTxt = new javax.swing.JLabel();
        ZonaDescansoTxt = new javax.swing.JLabel();
        ComedorTxt = new javax.swing.JLabel();
        ComidaTxt = new javax.swing.JLabel();
        Comida = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ZonaComun = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Comedor = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        ZonaDescanso1 = new javax.swing.JTextPane();
        ExterioirPanel = new javax.swing.JPanel();
        Zona4Txt = new javax.swing.JLabel();
        ExterioirH = new javax.swing.JLabel();
        ZombiesZ4 = new javax.swing.JTextField();
        HumanosZ1 = new javax.swing.JTextField();
        HumanosZ4 = new javax.swing.JTextField();
        ZombiesZ1 = new javax.swing.JTextField();
        Zona1Txt = new javax.swing.JLabel();
        Zona2Txt = new javax.swing.JLabel();
        ZombiesZ2 = new javax.swing.JTextField();
        HumanosZ2 = new javax.swing.JTextField();
        Zona3Txt = new javax.swing.JLabel();
        ZombiesZ3 = new javax.swing.JTextField();
        HumanosZ3 = new javax.swing.JTextField();
        ContBtn = new javax.swing.JButton();
        StopBtn = new javax.swing.JButton();
        TunelesPanel = new javax.swing.JPanel();
        TunelesH = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        GrupoSalidaT1 = new javax.swing.JTextPane();
        TunelTxt1 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        PasoT1 = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        GrupoEntradaT1 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        GrupoSalidaT2 = new javax.swing.JTextPane();
        TunelTxt2 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        PasoT2 = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        GrupoEntradaT2 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        GrupoSalidaT3 = new javax.swing.JTextPane();
        TunelTxt3 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        PasoT3 = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        GrupoEntradaT3 = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        GrupoSalidaT4 = new javax.swing.JTextPane();
        TunelTxt4 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        PasoT4 = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        GrupoEntradaT4 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RefugioPanel.setBackground(new java.awt.Color(0, 204, 255));
        RefugioPanel.setPreferredSize(new java.awt.Dimension(218, 482));

        RefugioH.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        RefugioH.setText("REFUGIO");

        ZonaComunTxt.setText("Zona Común");

        ZonaDescansoTxt.setText("Zona Descanso");

        ComedorTxt.setText("Comedor");

        ComidaTxt.setText("Comida:");

        Comida.setEditable(false);
        Comida.setText("0");
        Comida.setOpaque(true);
        Comida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComidaActionPerformed(evt);
            }
        });

        ZonaComun.setEditable(false);
        ZonaComun.setPreferredSize(new java.awt.Dimension(201, 109));
        jScrollPane2.setViewportView(ZonaComun);

        Comedor.setEditable(false);
        Comedor.setPreferredSize(new java.awt.Dimension(201, 109));
        jScrollPane3.setViewportView(Comedor);

        ZonaDescanso1.setEditable(false);
        ZonaDescanso1.setPreferredSize(new java.awt.Dimension(201, 109));
        jScrollPane4.setViewportView(ZonaDescanso1);

        javax.swing.GroupLayout RefugioPanelLayout = new javax.swing.GroupLayout(RefugioPanel);
        RefugioPanel.setLayout(RefugioPanelLayout);
        RefugioPanelLayout.setHorizontalGroup(
            RefugioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RefugioPanelLayout.createSequentialGroup()
                .addGroup(RefugioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RefugioPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(RefugioH))
                    .addGroup(RefugioPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ZonaComunTxt))
                    .addGroup(RefugioPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(RefugioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RefugioPanelLayout.createSequentialGroup()
                                .addComponent(ComedorTxt)
                                .addGap(37, 37, 37)
                                .addComponent(ComidaTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Comida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZonaDescansoTxt)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        RefugioPanelLayout.setVerticalGroup(
            RefugioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RefugioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RefugioH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ZonaComunTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ZonaDescansoTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RefugioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComedorTxt)
                    .addComponent(ComidaTxt)
                    .addComponent(Comida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        ExterioirPanel.setBackground(new java.awt.Color(196, 158, 17));
        ExterioirPanel.setPreferredSize(new java.awt.Dimension(214, 482));

        Zona4Txt.setText("Zona 4");

        ExterioirH.setBackground(new java.awt.Color(153, 153, 153));
        ExterioirH.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        ExterioirH.setText("EXTERIOR");

        ZombiesZ4.setEditable(false);

        HumanosZ1.setEditable(false);

        HumanosZ4.setEditable(false);

        ZombiesZ1.setEditable(false);

        Zona1Txt.setText("Zona 1");

        Zona2Txt.setText("Zona 2");

        ZombiesZ2.setEditable(false);

        HumanosZ2.setEditable(false);

        Zona3Txt.setText("Zona 3");

        ZombiesZ3.setEditable(false);

        HumanosZ3.setEditable(false);

        javax.swing.GroupLayout ExterioirPanelLayout = new javax.swing.GroupLayout(ExterioirPanel);
        ExterioirPanel.setLayout(ExterioirPanelLayout);
        ExterioirPanelLayout.setHorizontalGroup(
            ExterioirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExterioirPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExterioirH)
                .addGap(51, 51, 51))
            .addGroup(ExterioirPanelLayout.createSequentialGroup()
                .addGroup(ExterioirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExterioirPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ExterioirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExterioirPanelLayout.createSequentialGroup()
                                .addComponent(HumanosZ1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ZombiesZ1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExterioirPanelLayout.createSequentialGroup()
                                .addComponent(HumanosZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ZombiesZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ExterioirPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Zona1Txt))
                    .addGroup(ExterioirPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(Zona2Txt))
                    .addGroup(ExterioirPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ExterioirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExterioirPanelLayout.createSequentialGroup()
                                .addComponent(HumanosZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ZombiesZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExterioirPanelLayout.createSequentialGroup()
                                .addComponent(Zona4Txt)
                                .addGap(79, 79, 79))))
                    .addGroup(ExterioirPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ExterioirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ExterioirPanelLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(Zona3Txt)
                                .addGap(79, 79, 79))
                            .addGroup(ExterioirPanelLayout.createSequentialGroup()
                                .addComponent(HumanosZ3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ZombiesZ3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        ExterioirPanelLayout.setVerticalGroup(
            ExterioirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExterioirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ExterioirH)
                .addGap(18, 18, 18)
                .addComponent(Zona1Txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExterioirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZombiesZ1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HumanosZ1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Zona2Txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExterioirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZombiesZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HumanosZ2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Zona3Txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExterioirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HumanosZ3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ZombiesZ3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Zona4Txt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ExterioirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZombiesZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HumanosZ4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ContBtn.setBackground(new java.awt.Color(51, 255, 51));
        ContBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ContBtn.setText("CONTINUE");
        ContBtn.setToolTipText("");
        ContBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 0), new java.awt.Color(0, 255, 51), new java.awt.Color(51, 153, 0), new java.awt.Color(0, 153, 51)));
        ContBtn.setPreferredSize(new java.awt.Dimension(83, 45));
        ContBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContBtnActionPerformed(evt);
            }
        });

        StopBtn.setBackground(new java.awt.Color(255, 51, 51));
        StopBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        StopBtn.setText("STOP");
        StopBtn.setToolTipText("");
        StopBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(255, 51, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 51, 0)));
        StopBtn.setPreferredSize(new java.awt.Dimension(83, 45));
        StopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopBtnActionPerformed(evt);
            }
        });

        TunelesPanel.setBackground(new java.awt.Color(255, 255, 102));
        TunelesPanel.setPreferredSize(new java.awt.Dimension(240, 482));

        TunelesH.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        TunelesH.setText("TUNELES");

        GrupoSalidaT1.setEditable(false);
        GrupoSalidaT1.setPreferredSize(new java.awt.Dimension(64, 68));
        jScrollPane8.setViewportView(GrupoSalidaT1);

        TunelTxt1.setText("Tunel 1");

        PasoT1.setEditable(false);
        PasoT1.setPreferredSize(new java.awt.Dimension(88, 22));
        jScrollPane9.setViewportView(PasoT1);

        GrupoEntradaT1.setEditable(false);
        GrupoEntradaT1.setPreferredSize(new java.awt.Dimension(64, 68));
        jScrollPane17.setViewportView(GrupoEntradaT1);

        GrupoSalidaT2.setEditable(false);
        GrupoSalidaT2.setPreferredSize(new java.awt.Dimension(64, 68));
        jScrollPane10.setViewportView(GrupoSalidaT2);

        TunelTxt2.setText("Tunel 2");

        PasoT2.setEditable(false);
        PasoT2.setPreferredSize(new java.awt.Dimension(88, 22));
        jScrollPane11.setViewportView(PasoT2);

        GrupoEntradaT2.setEditable(false);
        GrupoEntradaT2.setPreferredSize(new java.awt.Dimension(64, 68));
        jScrollPane18.setViewportView(GrupoEntradaT2);

        GrupoSalidaT3.setEditable(false);
        GrupoSalidaT3.setPreferredSize(new java.awt.Dimension(64, 68));
        jScrollPane12.setViewportView(GrupoSalidaT3);

        TunelTxt3.setText("Tunel 3");

        PasoT3.setEditable(false);
        PasoT3.setPreferredSize(new java.awt.Dimension(88, 22));
        jScrollPane13.setViewportView(PasoT3);

        GrupoEntradaT3.setEditable(false);
        GrupoEntradaT3.setPreferredSize(new java.awt.Dimension(64, 68));
        jScrollPane19.setViewportView(GrupoEntradaT3);

        GrupoSalidaT4.setEditable(false);
        GrupoSalidaT4.setPreferredSize(new java.awt.Dimension(64, 68));
        jScrollPane14.setViewportView(GrupoSalidaT4);

        TunelTxt4.setText("Tunel 4");

        PasoT4.setEditable(false);
        PasoT4.setPreferredSize(new java.awt.Dimension(88, 22));
        jScrollPane15.setViewportView(PasoT4);

        GrupoEntradaT4.setEditable(false);
        GrupoEntradaT4.setPreferredSize(new java.awt.Dimension(64, 68));
        jScrollPane20.setViewportView(GrupoEntradaT4);

        javax.swing.GroupLayout TunelesPanelLayout = new javax.swing.GroupLayout(TunelesPanel);
        TunelesPanel.setLayout(TunelesPanelLayout);
        TunelesPanelLayout.setHorizontalGroup(
            TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TunelesPanelLayout.createSequentialGroup()
                .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(TunelesPanelLayout.createSequentialGroup()
                            .addContainerGap(6, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TunelesPanelLayout.createSequentialGroup()
                                    .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(TunelesPanelLayout.createSequentialGroup()
                                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(TunelTxt2))
                                        .addGroup(TunelesPanelLayout.createSequentialGroup()
                                            .addGap(69, 69, 69)
                                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TunelesPanelLayout.createSequentialGroup()
                                    .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(TunelesPanelLayout.createSequentialGroup()
                                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(TunelTxt3))
                                        .addGroup(TunelesPanelLayout.createSequentialGroup()
                                            .addGap(69, 69, 69)
                                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TunelesPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(TunelesPanelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(TunelTxt1))
                                    .addGroup(TunelesPanelLayout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TunelesPanelLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(TunelesH))))
                    .addGroup(TunelesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TunelesPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(TunelTxt4))
                            .addGroup(TunelesPanelLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        TunelesPanelLayout.setVerticalGroup(
            TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TunelesPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(TunelesH)
                .addGap(38, 38, 38)
                .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TunelesPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TunelesPanelLayout.createSequentialGroup()
                                .addComponent(TunelTxt1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(46, 46, 46)
                .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TunelesPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TunelesPanelLayout.createSequentialGroup()
                                .addComponent(TunelTxt2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(39, 39, 39)
                .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TunelesPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TunelesPanelLayout.createSequentialGroup()
                                .addComponent(TunelTxt3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TunelesPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(TunelesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(TunelesPanelLayout.createSequentialGroup()
                                .addComponent(TunelTxt4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jTextPane1.setEditable(false);
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RefugioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TunelesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExterioirPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ContBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(StopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TunelesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(StopBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ContBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RefugioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                            .addComponent(ExterioirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComidaActionPerformed

    private void ContBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContBtnActionPerformed
        // TODO add your handling code here:
        this.parado = false;
        this.espera_Control.notifyAll();
    }//GEN-LAST:event_ContBtnActionPerformed

    private void StopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopBtnActionPerformed
        // TODO add your handling code here:
        this.parado = true;
        new SimulacionParada().setVisible(true);
    }//GEN-LAST:event_StopBtnActionPerformed
    
    public void ha_parado() throws InterruptedException{
        if(parado){this.espera_Control.wait();}
    }
    
    public synchronized void mod_text_zonaComun(List<String> listaHumanos){ //reescribimos la lista. Para evitar condiciones de carrera, solo puede acceder uno a la vez, uso de synchronized
        StringBuilder texto = new StringBuilder();  // Usamos StringBuilder para acumular los resultados
        for (String IdH : listaHumanos) {
            texto.append(IdH).append("\n");  // Agregamos cada id a la cadena
        }
        // Ahora escribimos todo el texto en el JTextField
        this.ZonaComun.setText(texto.toString());
    }
    
    public synchronized void mod_text_descanso(List<String> listaHumanos){//reescribimos la lista. Para evitar condiciones de carrera, solo puede acceder uno a la vez, uso de synchronized
        StringBuilder texto = new StringBuilder();  // Usamos StringBuilder para acumular los resultados
        for (String IdH : listaHumanos) {
            texto.append(IdH).append("\n");  // Agregamos cada id a la cadena
        }
        // Ahora escribimos todo el texto en el JTextField
        this.ZonaComun.setText(texto.toString());
    }
    
    public synchronized void mod_text_comedor(List<String> listaHumanos){//reescribimos la lista. Para evitar condiciones de carrera, solo puede acceder uno a la vez, uso de synchronized
        StringBuilder texto = new StringBuilder();  // Usamos StringBuilder para acumular los resultados
        for (String IdH : listaHumanos) {
            texto.append(IdH).append("\n");  // Agregamos cada id a la cadena
        }
        // Ahora escribimos todo el texto en el JTextField
        this.Comedor.setText(texto.toString());
    }
    public synchronized void  mod_text_comida(int cantidad){//reescribimos la lista. Para evitar condiciones de carrera, solo puede acceder uno a la vez, uso de synchronized
        this.Comida.setText(String.valueOf(cantidad));
    }
        
    public void mod_text_tuneles_entrada(List<String> listaHumanos, int tunel) {
        Semaphore[] semaforos = {null,stsr1, stsr2, stsr3, stsr4};
        JTextPane[] paneles = {null,GrupoEntradaT1, GrupoEntradaT2, GrupoEntradaT3, GrupoEntradaT4};
        try {
            semaforos[tunel].acquire();

            StringBuilder texto = new StringBuilder();
            for (String IdH : listaHumanos) {
                texto.append(IdH).append("\n");
            }

            paneles[tunel].setText(texto.toString());
        } catch (InterruptedException e) {
            e.printStackTrace();
        } finally {
            semaforos[tunel].release();
        }
    }
    public void mod_text_tuneles_salida(List<String> listaHumanos, int tunel) {
        Semaphore[] semaforos = {null,stsr1, stsr2, stsr3, stsr4};
        JTextPane[] paneles = {null,GrupoSalidaT1, GrupoSalidaT2, GrupoSalidaT3, GrupoSalidaT4};

        try {
            semaforos[tunel].acquire();

            StringBuilder texto = new StringBuilder();
            for (String IdH : listaHumanos) {
                texto.append(IdH).append("\n");
            }

            paneles[tunel].setText(texto.toString());
        } catch (InterruptedException e) {
            e.printStackTrace();
        } finally {
            semaforos[tunel].release();
        }
    }
    
    public void mod_text_paso_tunel(String IdH, int tunel){
        JTextPane[] paneles = {null,PasoT1, PasoT2, PasoT3, PasoT4};

        if(IdH == null){
                paneles[tunel].setText("");}
        else{
             paneles[tunel].setText(IdH);}    
    }

                
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazP1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane Comedor;
    private javax.swing.JLabel ComedorTxt;
    private javax.swing.JTextField Comida;
    private javax.swing.JLabel ComidaTxt;
    private javax.swing.JButton ContBtn;
    private javax.swing.JLabel ExterioirH;
    private javax.swing.JPanel ExterioirPanel;
    private javax.swing.JTextPane GrupoEntradaT1;
    private javax.swing.JTextPane GrupoEntradaT2;
    private javax.swing.JTextPane GrupoEntradaT3;
    private javax.swing.JTextPane GrupoEntradaT4;
    private javax.swing.JTextPane GrupoSalidaT1;
    private javax.swing.JTextPane GrupoSalidaT2;
    private javax.swing.JTextPane GrupoSalidaT3;
    private javax.swing.JTextPane GrupoSalidaT4;
    private javax.swing.JTextField HumanosZ1;
    private javax.swing.JTextField HumanosZ2;
    private javax.swing.JTextField HumanosZ3;
    private javax.swing.JTextField HumanosZ4;
    private javax.swing.JTextPane PasoT1;
    private javax.swing.JTextPane PasoT2;
    private javax.swing.JTextPane PasoT3;
    private javax.swing.JTextPane PasoT4;
    private javax.swing.JLabel RefugioH;
    private javax.swing.JPanel RefugioPanel;
    private javax.swing.JButton StopBtn;
    private javax.swing.JLabel TunelTxt1;
    private javax.swing.JLabel TunelTxt2;
    private javax.swing.JLabel TunelTxt3;
    private javax.swing.JLabel TunelTxt4;
    private javax.swing.JLabel TunelesH;
    private javax.swing.JPanel TunelesPanel;
    private javax.swing.JTextField ZombiesZ1;
    private javax.swing.JTextField ZombiesZ2;
    private javax.swing.JTextField ZombiesZ3;
    private javax.swing.JTextField ZombiesZ4;
    private javax.swing.JLabel Zona1Txt;
    private javax.swing.JLabel Zona2Txt;
    private javax.swing.JLabel Zona3Txt;
    private javax.swing.JLabel Zona4Txt;
    private javax.swing.JTextPane ZonaComun;
    private javax.swing.JLabel ZonaComunTxt;
    private javax.swing.JTextPane ZonaDescanso1;
    private javax.swing.JLabel ZonaDescansoTxt;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
